# Generated by Django 5.1 on 2024-08-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tech_stack',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('csharp', 'C#'), ('cpp', 'C++'), ('ruby', 'Ruby'), ('php', 'PHP'), ('swift', 'Swift'), ('go', 'Go'), ('rust', 'Rust'), ('other', 'Other')], default='', max_length=20, null=True),
        ),
    ]
