# Generated by Django 5.1 on 2024-08-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_tech_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='editor',
            field=models.CharField(blank=True, choices=[('Vim', 'Vim'), ('EMACS', 'EMACS'), ('VS Code', 'VS Code'), ('Sublime Text', 'Sublime Text'), ('Atom', 'Atom'), ('PyCharm', 'PyCharm'), ('Notepad++', 'Notepad++'), ('Other', 'Other')], default=None, max_length=20, null=True),
        ),
    ]
