# Generated by Django 5.1 on 2024-08-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='os',
            field=models.CharField(blank=True, choices=[('Windows', 'Windows'), ('MacOS', 'MacOS'), ('Linux', 'Linux'), ('Ubuntu', 'Ubuntu'), ('Fedora', 'Fedora'), ('Solaris', 'Solaris'), ('Other', 'Other')], default=None, max_length=10, null=True),
        ),
    ]
