# Generated by Django 5.1 on 2024-09-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.TextField(blank=True, help_text='Enter your interests, separated by commas', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='languages',
            field=models.JSONField(blank=True, default=list, help_text='List of languages known', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='seeking',
            field=models.CharField(blank=True, choices=[('relationship', 'Relationship'), ('casual', 'Casual'), ('figuring_out', 'Figuring Out')], max_length=20, null=True),
        ),
    ]
