# Generated by Django 5.1 on 2024-09-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_interests_profile_languages_profile_seeking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='languages',
            field=models.TextField(blank=True, help_text='List of languages known', null=True),
        ),
    ]
